#!/usr/bin/env bash
# New ubuntu machine installing
# Nginx on port 80
# Serve to return a Hello World strg

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Debuting nginx service
sudo service nginx start

# Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Website files ownership to the user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# New index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
